# Generated by Django 3.2.16 on 2026-01-27 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Perim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerimSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('masterid', models.IntegerField(primary_key=True, serialize=False)),
                ('storeid', models.IntegerField()),
                ('storename', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('yearbuilt', models.IntegerField(blank=True, null=True)),
                ('totalsqft', models.IntegerField(blank=True, null=True)),
                ('rentablesqft', models.IntegerField(blank=True, null=True)),
                ('storetype', models.CharField(blank=True, max_length=50, null=True)),
                ('companytype', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorePerim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('perim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.perim')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.store')),
            ],
        ),
        migrations.CreateModel(
            name='StorageBoundary',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.boundary',),
        ),
        migrations.CreateModel(
            name='StorageStudy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.study',),
        ),
        migrations.CreateModel(
            name='SupplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('perimset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.perimset')),
                ('perimweight', models.ManyToManyField(through='storage.ModelWeights', to='storage.Perim')),
            ],
        ),
        migrations.CreateModel(
            name='StorePerimBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.FloatField()),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('storeperim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storeperim')),
                ('supplymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.supplymodel')),
            ],
        ),
        migrations.AddField(
            model_name='perim',
            name='perimset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.perimset'),
        ),
        migrations.AddField(
            model_name='perim',
            name='store',
            field=models.ManyToManyField(through='storage.StorePerim', to='storage.Store'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='perim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.perim'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='supplymodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.supplymodel'),
        ),
        migrations.CreateModel(
            name='DemandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fields', models.ManyToManyField(through='storage.Coefficient', to='main.Characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='DemandAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.FloatField(blank=True, null=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('demandmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.demandmodel')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.study')),
            ],
        ),
        migrations.AddField(
            model_name='coefficient',
            name='demandmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.demandmodel'),
        ),
        migrations.AddField(
            model_name='coefficient',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.characteristic'),
        ),
        migrations.CreateModel(
            name='BoundaryPerim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('perim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.perim')),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.FloatField()),
                ('supply', models.FloatField()),
                ('residual', models.FloatField()),
                ('residualgraphic', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('demandmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.demandmodel')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.study')),
                ('supplymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.supplymodel')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.FloatField(blank=True, null=True)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.study')),
                ('supplymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.supplymodel')),
            ],
            options={
                'unique_together': {('supplymodel', 'boundary')},
            },
        ),
    ]
