# Generated by Django 3.2.16 on 2022-12-12 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.field')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StoreIso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreIsoWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('storeiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storeiso')),
            ],
        ),
        migrations.CreateModel(
            name='StoreIsoWeighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storeiso', models.ManyToManyField(through='storage.StoreIsoWeight', to='storage.StoreIso')),
            ],
        ),
        migrations.AddField(
            model_name='storeisoweight',
            name='storeisoweighting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.storeisoweighting'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('field', models.ManyToManyField(through='storage.Coefficient', to='census.Field')),
            ],
        ),
        migrations.AddField(
            model_name='coefficient',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.model'),
        ),
    ]
