# Generated by Django 3.2.16 on 2022-12-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20221213_1548'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='DemandModel',
        ),
    ]
