# Generated by Django 3.2.16 on 2022-12-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_model_demandmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsoTime',
            fields=[
                ('time', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='demandmodel',
            old_name='field',
            new_name='fields',
        ),
        migrations.RemoveField(
            model_name='coefficient',
            name='model',
        ),
        migrations.RemoveField(
            model_name='storeisoweight',
            name='storeiso',
        ),
        migrations.RemoveField(
            model_name='storeisoweighting',
            name='storeiso',
        ),
        migrations.AddField(
            model_name='coefficient',
            name='demandmodel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='storage.demandmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeisoweight',
            name='time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='storage.isotime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeisoweighting',
            name='weights',
            field=models.ManyToManyField(through='storage.StoreIsoWeight', to='storage.IsoTime'),
        ),
        migrations.AlterField(
            model_name='storeiso',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storage.isotime'),
        ),
    ]
