# Generated by Django 3.2.16 on 2022-12-15 12:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20221214_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4269),
        ),
        migrations.AlterField(
            model_name='storeiso',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
        ),
    ]
