# Generated by Django 3.2.16 on 2026-01-27 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DABoundary',
            fields=[
                ('dauid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dguid', models.CharField(max_length=21)),
                ('landarea', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pruid', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3347)),
            ],
        ),
    ]
