# Generated by Django 3.2.16 on 2022-12-12 16:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=4, max_digits=30)),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.boundary')),
            ],
        ),
        migrations.CreateModel(
            name='DABoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dauid', models.CharField(max_length=25)),
                ('dguid', models.CharField(max_length=25)),
                ('landarea', models.FloatField()),
                ('pruid', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('geometry', models.ManyToManyField(through='census.BoundaryData', to='census.Boundary')),
            ],
        ),
        migrations.AddField(
            model_name='boundarydata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.field'),
        ),
    ]
