# Generated by Django 4.1 on 2024-02-15 22:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGBoundary',
            fields=[
                ('statefp', models.CharField(max_length=2)),
                ('countyfp', models.CharField(max_length=3)),
                ('tractce', models.CharField(max_length=6)),
                ('blkgrpce', models.CharField(max_length=1)),
                ('affgeoid', models.CharField(max_length=21)),
                ('geoid', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('namelsad', models.CharField(max_length=100)),
                ('lsad', models.CharField(max_length=100)),
                ('aland', models.BigIntegerField(null=True)),
                ('awater', models.BigIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4629)),
            ],
        ),
        migrations.CreateModel(
            name='DABoundary',
            fields=[
                ('dauid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('dguid', models.CharField(max_length=21)),
                ('landarea', models.DecimalField(decimal_places=4, max_digits=12)),
                ('pruid', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3347)),
            ],
        ),
    ]
