# Generated by Django 3.2.16 on 2022-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_auto_20221213_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='geometry',
        ),
        migrations.AddField(
            model_name='field',
            name='boundary',
            field=models.ManyToManyField(through='census.BoundaryData', to='census.Boundary'),
        ),
        migrations.AlterField(
            model_name='daboundary',
            name='dauid',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='daboundary',
            name='dguid',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='daboundary',
            name='landarea',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='daboundary',
            name='pruid',
            field=models.CharField(max_length=2),
        ),
    ]
