# Generated by Django 3.2.16 on 2022-12-16 23:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20221215_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3347),
        ),
        migrations.AlterField(
            model_name='daboundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=3347),
        ),
    ]
