# Generated by Django 3.2.16 on 2026-01-27 18:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.characteristic')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('country', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=2)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
                ('characteristics', models.ManyToManyField(blank=True, to='main.Characteristic')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.boundary')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.characteristic')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.study')),
            ],
        ),
        migrations.AddField(
            model_name='boundary',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.study'),
        ),
        migrations.AddConstraint(
            model_name='boundary',
            constraint=models.UniqueConstraint(fields=('study', 'ext_id'), name='unique_constraint'),
        ),
    ]
